name: 🐛 New Bug Report
description: Help Pulsar improve by filing a bug report
labels: ["bug", "triage", "question", "modernization"]
body:
- type: checkboxes
  id: initiative-check
  attributes:
    label: Thanks in advance for your bug report!
    description: "Please make sure you have done the following:"
    options:
      - label: Have you reproduced in [safe mode](https://pulsar-edit.dev/docs/atom-archive/faq/sections/what-does-safe-mode-do.html)? 
        required: true
      - label: Have you used the [debugging guide](https://pulsar-edit.dev/docs/atom-archive/hacking-atom/#debugging) to fix any issues? 
        required: true
      - label: "Checked our [FAQs](https://pulsar-edit.dev/docs/launch-manual/sections/faq/) to make sure your question isn't answered there?"
        required: true
      - label: Does your issue already [exist](https://github.com/issues?q=is%3Aissue+user%3Apulsar-edit+is%3Aopen)? 
        required: true
      - label: You are the latest release of Pulsar?
        required: true
- type: textarea
  id: what-happened
  attributes:
    label: What happened?
    placeholder: Tell us what happened!
    required: true
- type: dropdown
  id: os-info
  attributes:
    label: Which OS does this happen on?
    options:
      - Debian based (Linux Mint, Ubuntu, etc.)
      - Arch based (Manjaro, Garuda, etc.)
      - Red Hat based (Fedora, Alma, RockyLinux, CentOS Stream, etc.)
      - OpenSUSE based
      - macOS
      - Windows
      - Other(Please specify in the OS details field below)
  validations:
    required: true
- type: textarea
  id: os-version
  attributes:
    label: OS details
    placeholder: OS version
    required: true
- type: dropdown
  id: sys-info
  attributes:
    label: Which CPU architecture are you running this on?
    options:
      - 64-bit(x86_64)
      - Apple M1/M2
  validations:
    required: false
- type: textarea
  id: steps
  attributes:
    label: What steps are needed to reproduce this?
    placeholder: |
      1. In this environment...
      2. With this config...
      3. Run '...'
      4. See error...
  validations:
    required: true
- type: textarea
  id: additional-context
  attributes:
    description: |
      "What other details can you provide?"
    label: "Additional Information:"
    placeholder: |
      Add any other information or screenshots relating to the bug here. |
      If building from source please provide the commit hash here.
  validations:
    required: false
