name: Feature request
description: Got an idea for us?
title: ":bulb: [Feature: ]"
labels: ["enhancement", "documentation"]
body:
  - type: text-area
    id: summary
    label: Summary
    placeholder: |
      Please give a detailed explanation of the feature you need.
  validations:
    required: true
  - type: textarea
    id: movtivation
    description: What is the motivation for doing this?
    attributes:
      label: "Enter your response below:"
      placeholder: What's the reasoning for adding this feature and/or package? What uses are there for this?
    validations:
      required: true
  - type: input
    id: alternatives
    description: |
      Are there any other possible alternatives? (Is this really the best solution or only option to add this feature? Could it be a plugin?)
    attributes:
      placeholder: |
        A clear and concise description of the alternative solutions you've considered. Be sure to explain why Atom's existing customizability isn't suitable for this feature.
    validations:
      required: true
  - type: input
    id: additional-context
    description: |
      Please provide any additional context for this:
    attributes:
      placeholder: |
        Add any other context or screenshots about the feature request here.
