
name : Update News Section

on :
    workflow_dispatch :

    push :

        branches :
            
            -   'main'
            
        paths :
            
            -   'News/Data/News.yaml'


concurrency:

    cancel-in-progress : true
    group : news


jobs :
    Build :

        runs-on : ubuntu-latest

        steps :

            -   name : Checkout
                uses : actions/checkout@v3

            -   name : Setup Deno
                uses : denoland/setup-deno@v1
                with :
                    
                    deno-version : v1.29
                
            -   name : Run Updater
                working-directory: ./News
                run : deno task update
                
            -   name : Commit Page
                uses : EndBug/add-and-commit@v9
                with :
                    
                    default_author : github_actor
                    message : Updated News Section
                    add : profile/README.md
